name: Vue project Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM
        run: npm ci
        
      - name: Npm Run Build
        run: npm run build


        
